// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6NhlEFx2NIfsUbiFPOdeeP0OldsEGE6c',
    appId: '1:100182720078:web:04918da7064f71c6290d1f',
    messagingSenderId: '100182720078',
    projectId: 'fir-group-a580d',
    authDomain: 'fir-group-a580d.firebaseapp.com',
    storageBucket: 'fir-group-a580d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd1VA76cdsoo0CtmMl5whFgmIShJgHxnE',
    appId: '1:100182720078:android:2e205f47857543e5290d1f',
    messagingSenderId: '100182720078',
    projectId: 'fir-group-a580d',
    storageBucket: 'fir-group-a580d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCPOIkUD4Mgq9JTPvmJEfmP4_pcbbrDLQ',
    appId: '1:100182720078:ios:9ee9e107e52a4cbd290d1f',
    messagingSenderId: '100182720078',
    projectId: 'fir-group-a580d',
    storageBucket: 'fir-group-a580d.appspot.com',
    iosClientId: '100182720078-ijulmfjoimckvjqdq5ke98sg0a489aao.apps.googleusercontent.com',
    iosBundleId: 'com.example.dcit24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCPOIkUD4Mgq9JTPvmJEfmP4_pcbbrDLQ',
    appId: '1:100182720078:ios:9ee9e107e52a4cbd290d1f',
    messagingSenderId: '100182720078',
    projectId: 'fir-group-a580d',
    storageBucket: 'fir-group-a580d.appspot.com',
    iosClientId: '100182720078-ijulmfjoimckvjqdq5ke98sg0a489aao.apps.googleusercontent.com',
    iosBundleId: 'com.example.dcit24',
  );
}
